[workspace]
members = [
  "effects/effects-lib",
  "effects/decrypt",
  "effects/glitch",
  "effects/wasm-matrix",
]
resolver = "2"

[workspace.dependencies]
xfetch-effect-api = { version = "0.2.0", package = "xfetch-effect-api" }
xfetch-effects-lib = { version = "0.2.0", path = "effects/effects-lib", package = "xfetch-effects-lib" }

